spring:
  config:
    import: aws-secretsmanager:prod/mixchat/app-secrets
  cloud:
    aws:
      region:
        static: ap-northeast-2

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
      endpoint: https://s3.ap-northeast-2.amazonaws.com
      path-style-access: false

#   datasource:
#     url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}
#     username: ${MYSQL_USER}
#     password: ${MYSQL_PASSWORD}
#   data:
#     mongodb:
#       uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/${MONGO_DB}?authSource=admin
#     redis:
#       host: ${REDIS_HOST}
#       port: ${REDIS_PORT}
#       password: ${REDIS_PASSWORD}

# server:
#   port: 8080

# logging:
#   level:
#     org.hibernate.orm.jdbc.bind: INFO
#     org.hibernate.orm.jdbc.extract: INFO
#     org.springframework.transaction.interceptor: INFO
#     com.back: INFO
# custom:
#   site:
#     cookieDomain: "${custom.prod.cookieDomain}"
#     frontUrl: "${custom.prod.frontUrl}"
#     backUrl: "${custom.prod.backUrl}"
#     name: mixchat
# # 운영 단계에선 actuator 전용 포트 사용
# management:
#   server:
#     port: 9100
